name: Publish Release
on:
  release:
    types:
    - published
jobs:
  test:
    name: ${{ matrix.lang }} tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        lang: [Python]

    steps:
    - uses: actions/checkout@v2

    - name: Publish distribution to PyPI
      run: echo "hello world"
